---
# =============================================================================
# Molecule - Playbook de test pour le rôle ssh-chroot-jail
# =============================================================================

- name: Converge
  hosts: all
  become: true

  vars:
    # Utilisateurs de test
    ssh_chroot_jail_users:
      # Alice : SFTP only (allow_interactive: false par défaut)
      - name: alice
        home: /home_local/alice
        authorized_keys: []
        bind_remounts: []

      # Bob : Shell interactif dans la jail
      - name: bob
        home: /home_local/bob
        allow_interactive: true
        authorized_keys: []
        extra_bins:
          - /usr/bin/git
        bind_remounts: []

      # Charlie : SFTP avec exception (tunnel MySQL)
      - name: charlie
        home: /home_local/charlie
        allow_interactive: false
        authorized_keys: []
        sshd_user_options:
          - "AllowTcpForwarding yes"
          - "PermitOpen 127.0.0.1:3306"

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
